config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  delete 'bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to @list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.includes(:movie).where(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<main>
  <%= link_to 'Back', list_path(@list), class: 'btn btn-outline-secondary m-2' %>
  <div class="container">
    <h1 class="mt-2 mb-5">Add a Movie to <%= @list.name %></h1>
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment %>
      <%= f.submit 'Add', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<main>
  <div class="container">
    <h1 class="my-5">Movies Lists</h1>
    <%= link_to 'New list', new_list_path, class: 'btn btn-secondary' %>
    <div class="container">
      <div class="row">
        <% @lists.each do |list| %>
          <div class="col-sm-12 col-md-6 col-lg-4 col-xl-3">
            <%= link_to list_path(list), class:'card-link' do %>
              <div class="card card-mine card-small card-clickable" style="background-image: url('<%= cl_image_path list.photo.key %>'); background-size: cover;">
                <h2><%= list.name %></h2>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/lists/new.html.erb
<main>
  <%= link_to 'Back', lists_path, class: 'btn btn-outline-secondary m-2' %>
  <div class="container">
    <h1 class="mt-2 mb-5">New List</h1>
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit 'Create', class: 'btn btn-secondary' %>
    <% end %>
  </div>
</main>

app/views/lists/show.html.erb
<main>
  <%= link_to 'Back', lists_path, class: 'btn btn-outline-secondary m-2' %>
  <div class="container">
    <h1 class="mt-2 mb-5"><%= @list.name %></h1>
    <%= link_to 'Add a movie', new_list_bookmark_path(@list), class: 'btn btn-secondary' %>
    <% @bookmarks.each do |bookmark| %>
      <div class="d-flex card-mine">
        <%= image_tag bookmark.movie.poster_url, alt: '', width: 200, class: 'mr-3' %>
        <div>
          <h2 class="mb-3"><%= bookmark.movie.title %></h2>
          <p><%= bookmark.movie.overview %></p>
          <p><%= bookmark.comment %></p>
          <% if !bookmark.movie.rating.nil? %>
            <p>Rating: <%= bookmark.movie.rating %></p>
          <% end %>
          <%= link_to 'Delete',
                      delete_bookmark_path(bookmark),
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>
</main>